Revert "Upgrade googletest to 41b5f149ab306e96b5b2faf523505d75acffd98a"
This reverts commit 3bfe1208647b9ff43b0401eb9a912f0922a52196.

Reason for revert: go/ab/emu-master-dev windows build still broken

https://android-build.googleplex.com/builds/submitted/6197151/sdk_tools_windows/latest/view/logs/build.log

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc(311,28): error: field type 'MockCFIRuleParserHandler' is an abstract class

01:26:37(02:24.0 ) rel | MockCFIRuleParserHandler mock_handler;

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\qemu\..\google-breakpad\src\processor/cfi_frame_info.h(151,18): note: unimplemented pure virtual method 'CFARule' in 'MockCFIRuleParserHandler'

01:26:37(02:24.0 ) rel | virtual void CFARule(const string &expression) = 0;

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\qemu\..\google-breakpad\src\processor/cfi_frame_info.h(152,18): note: unimplemented pure virtual method 'RARule' in 'MockCFIRuleParserHandler'

01:26:37(02:24.0 ) rel | virtual void RARule(const string &expression) = 0;

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\qemu\..\google-breakpad\src\processor/cfi_frame_info.h(155,18): note: unimplemented pure virtual method 'RegisterRule' in 'MockCFIRuleParserHandler'

01:26:37(02:24.0 ) rel | virtual void RegisterRule(const string &name, const string &expression) = 0;

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | In file included from C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc:37:

01:26:37(02:24.0 ) rel | In file included from C:\buildbot\src\android\emu-master-dev\external\qemu\..\google-breakpad\src\breakpad_googletest_includes.h:33:

01:26:37(02:24.0 ) rel | In file included from C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/gtest.h:62:

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(470,40): error: cannot initialize return object of type 'testing::Test *' with an rvalue of type 'Parser_Empty_Test *'

01:26:37(02:24.0 ) rel | Test* CreateTest() override { return new TestClass; }

01:26:37(02:24.0 ) rel | ^~~

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc(317,1): note: in instantiation of member function 'testing::internal::TestFactoryImpl<Parser_Empty_Test>::CreateTest' requested here

01:26:37(02:24.0 ) rel | TEST_F(Parser, Empty) {

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/gtest.h(2373,3): note: expanded from macro 'TEST_F'

01:26:37(02:24.0 ) rel | GTEST_TEST_(test_fixture, test_name, test_fixture, \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(1428,15): note: expanded from macro 'GTEST_TEST_'

01:26:37(02:24.0 ) rel | new ::testing::internal::TestFactoryImpl<GTEST_TEST_CLASS_NAME_(    \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(470,40): error: cannot initialize return object of type 'testing::Test *' with an rvalue of type 'Parser_LoneColon_Test *'

01:26:37(02:24.0 ) rel | Test* CreateTest() override { return new TestClass; }

01:26:37(02:24.0 ) rel | ^~~

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc(321,1): note: in instantiation of member function 'testing::internal::TestFactoryImpl<Parser_LoneColon_Test>::CreateTest' requested here

01:26:37(02:24.0 ) rel | TEST_F(Parser, LoneColon) {

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/gtest.h(2373,3): note: expanded from macro 'TEST_F'

01:26:37(02:24.0 ) rel | GTEST_TEST_(test_fixture, test_name, test_fixture, \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(1428,15): note: expanded from macro 'GTEST_TEST_'

01:26:37(02:24.0 ) rel | new ::testing::internal::TestFactoryImpl<GTEST_TEST_CLASS_NAME_(    \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(470,40): error: cannot initialize return object of type 'testing::Test *' with an rvalue of type 'Parser_CFANoExpr_Test *'

01:26:37(02:24.0 ) rel | Test* CreateTest() override { return new TestClass; }

01:26:37(02:24.0 ) rel | ^~~

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc(325,1): note: in instantiation of member function 'testing::internal::TestFactoryImpl<Parser_CFANoExpr_Test>::CreateTest' requested here

01:26:37(02:24.0 ) rel | TEST_F(Parser, CFANoExpr) {

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/gtest.h(2373,3): note: expanded from macro 'TEST_F'

01:26:37(02:24.0 ) rel | GTEST_TEST_(test_fixture, test_name, test_fixture, \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(1428,15): note: expanded from macro 'GTEST_TEST_'

01:26:37(02:24.0 ) rel | new ::testing::internal::TestFactoryImpl<GTEST_TEST_CLASS_NAME_(    \

01:26:37(02:24.0 ) rel | ^

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\googletest\googletest\include\gtest/internal/gtest-internal.h(470,40): error: cannot initialize return object of type 'testing::Test *' with an rvalue of type 'Parser_CFANoColonNoExpr_Test *'

01:26:37(02:24.0 ) rel | Test* CreateTest() override { return new TestClass; }

01:26:37(02:24.0 ) rel | ^~~

01:26:37(02:24.0 ) rel | C:\buildbot\src\android\emu-master-dev\external\google-breakpad\src\processor\cfi_frame_info_unittest.cc(329,1): note: in instantiation of member function 'testing::internal::TestFactoryImpl<Parser_CFANoColonNoExpr_Test>::CreateTest' requested here

01:26:37(02:24.0 ) rel | TEST_F(Parser, CFANoColonNoExpr) {

01:26:37(02:24.0 ) rel | ^
Change-Id: I15d70584259d243419ab9ef0d8c66b1710e3f9f9